apiVersion: v2
name: datadog
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: datadog
    version: 3.39.1
    repository: https://helm.datadoghq.com

